<?php

define("BASE_URL", "/SCSU-CSC400/");
define("ROOT_PATH", $_SERVER["DOCUMENT_ROOT"] . "/SCSU-CSC400/");

if (!defined("COMPANY_NAME")) define("COMPANY_NAME", "Southern Connecticut State University");
if (!defined("COPYYEAR")) define("COPYYEAR", "2025");

if (!defined("SITE_NAME")) define("SITE_NAME", "OwlMind");

if (!defined("NAV_ITEM_ONE")) define("NAV_ITEM_ONE", "Home");
if (!defined("NAV_ITEM_TWO")) define("NAV_ITEM_TWO", "Appointments");
if (!defined("NAV_ITEM_THREE")) define("NAV_ITEM_THREE", "Appointments");
if (!defined("NAV_ITEM_FOUR")) define("NAV_ITEM_FOUR", "Journal");
if (!defined("NAV_ITEM_FIVE")) define("NAV_ITEM_FIVE", "Mood Recorder");
if (!defined("NAV_ITEM_SIX")) define("NAV_ITEM_SIX", "Resources");
if (!defined("NAV_ITEM_SEVEN")) define("NAV_ITEM_SEVEN", "My Profile");
if (!defined("NAV_ITEM_EIGHT")) define("NAV_ITEM_EIGHT", "About Us");

?>
